In [2]:
# PS - Iris Dataset Operations

import pandas as pd

# Load Dataset
df = pd.read_csv("/content/Iris.csv", header=None)

# Column Names
df.columns = [
    "sepal_length",
    "sepal_width",
    "petal_length",
    "petal_width",
    "species"
]

print("Original Dataset")
display(df.head())

# ---------------------------------------------------
# 1. Create Subsets
# ---------------------------------------------------

setosa = df[df["species"] == "Iris-setosa"]
versicolor = df[df["species"] == "Iris-versicolor"]

print("Setosa Data")
display(setosa.head())

# ---------------------------------------------------
# 2. Merge Subsets
# ---------------------------------------------------

merged = pd.concat([setosa, versicolor])

print("Merged Data")
display(merged.head())

# ---------------------------------------------------
# 3. Sort Data
# ---------------------------------------------------

sorted_data = df.sort_values(by="petal_length")

print("Sorted Data")
display(sorted_data.head())

# ---------------------------------------------------
# 4. Transpose Data
# ---------------------------------------------------

print("Transpose Data")
display(df.head().T)

# ---------------------------------------------------
# 5. Melt Data
# ---------------------------------------------------

melted = pd.melt(
    df.head(),
    id_vars=["species"]
)

print("Melted Data")
display(melted.head())

# ---------------------------------------------------
# 6. Pivot Table
# ---------------------------------------------------

pivot = df.pivot_table(
    values="petal_length",
    index="species",
    aggfunc="mean"
)

print("Pivot Table")
display(pivot)

Original Dataset

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Setosa Data

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Merged Data

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Sorted Data

    sepal_length  sepal_width  petal_length  petal_width      species
22           4.6          3.6           1.0          0.2  Iris-setosa
13           4.3          3.0           1.1          0.1  Iris-setosa
14           5.8          4.0           1.2          0.2  Iris-setosa
35           5.0          3.2           1.2          0.2  Iris-setosa
16           5.4          3.9           1.3          0.4  Iris-setosa

Transpose Data

                        0            1            2            3            4
sepal_length          5.1          4.9          4.7          4.6          5.0
sepal_width           3.5          3.0          3.2          3.1          3.6
petal_length          1.4          1.4          1.3          1.5          1.4
petal_width           0.2          0.2          0.2          0.2          0.2
species       Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa  Iris-setosa

Melted Data

       species      variable  value
0  Iris-setosa  sepal_length    5.1
1  Iris-setosa  sepal_length    4.9
2  Iris-setosa  sepal_length    4.7
3  Iris-setosa  sepal_length    4.6
4  Iris-setosa  sepal_length    5.0

Pivot Table

                 petal_length
species
Iris-setosa             1.464
Iris-versicolor         4.260
Iris-virginica          5.552